language: generic
sudo: required

services:
  - docker

script:
  - docker run -v $PWD:/repo greenaddress/core_builder_for_android@sha256:09a9a65de8ba90a9d3334ea89f9924cdbcc2fdee424c175cc9e3b0d8702f05e0 /bin/bash -c "/repo/daemon_builder/fetchbuild.sh https://github.com/bitcoin/bitcoin/archive/v0.15.1.tar.gz"
    - docker run -v $PWD:/repo greenaddress/core_builder_for_android@sha256:09a9a65de8ba90a9d3334ea89f9924cdbcc2fdee424c175cc9e3b0d8702f05e0 /bin/bash -c "/repo/daemon_builder/fetchbuild.sh https://github.com/bitcoinknots/bitcoin/archive/v0.15.1.knots20171111.tar.gz"
