language: android

android:
    components:
        - tools
        - build-tools-26.0.1
        - android-26
        - platform-tools-26
        - extra-android-support
        - extra-android-m2repository
        - extra-google-m2repository
    licenses:
        - '.+'

before_script:
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-audio -no-window &
jdk:
    - oraclejdk8

script:
    - "./gradlew clean assembleRelease"
    - "android-wait-for-emulator"
    - "./gradlew cAT"
