language: android

android:
    components:
        - tools
        - build-tools-25.0.0
        - android-25
        - platform-tools-25
        - extra-android-support
        - extra-android-m2repository
        - extra-google-m2repository
    licenses:
        - '.+'

before_script:
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator

jdk:
    - oraclejdk8

script:
    - "./gradlew clean assembleRelease"
    - "./gradlew cAT"
